name: Just a test

on: [push]

jobs:
  branch-a:
    runs-on: ubuntu-latest
    name: Branch A
    steps:
      - name: Step A1
        run: sleep 60 && echo 'A1'
  branch-b:
    runs-on: ubuntu-latest
    name: Branch B
    steps:
      - name: Step B1
        run: sleep 5 && echo 'B1'
  branch-c:
    runs-on: ubuntu-latest
    needs: [branch-a, branch-b]
    name: Joining branch
    steps:
      - name: Joining A & B
        run: echo I am done!
